AWSTemplateFormatVersion: "2010-09-09"
Description: Endpoint template

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
# ------------------------------------------------------------#
# VPC Endpoint
# ------------------------------------------------------------# 
  S3VPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Gateway"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      PrivateDnsEnabled: false # must be false if it is gateway type

  SSMVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds: 
        - !Ref SubnetId  
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  SSMMessagesVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      SubnetIds: 
        - !Ref SubnetId  
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  EC2MessagesVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId        
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      SubnetIds: 
        - !Ref SubnetId  
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref SecurityGroupId

  ECRApiVPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
      SubnetIds: 
        - !Ref SubnetId
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId

  ECRDkrVPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      SubnetIds: 
        - !Ref SubnetId  
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId

  CloudwatchLogsVPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: 
        - !Ref SubnetId  
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId

  CloudwatchMonitoringEC2VPCEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcEndpointType: "Interface"
      VpcId: !Ref VpcId
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.monitoring"
      SubnetIds: 
        - !Ref SubnetId  
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref SecurityGroupId
