apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-apn1-eks-cluster
  region: ap-northeast-1
  version: "1.31"

iam:
  withOIDC: true
  # required for karpenter

autoModeConfig:
  enabled: true
  # nodePools: []
  # if you need to create your own NodePool, uncomment above so that default NodePool will not prioritized.

vpc:
  id: "vpc-id"
  # fill out the vpc-id
  controlPlaneSecurityGroupIDs:
    - "sg-id"
  # fill out the controle plane sd to access to the api server when the cluster is created
  subnets:
    private:
      ap-northeast-1a:
          id: "subnet-id"
      ap-northeast-1c:
          id: "subnet-id"
          # fill out the subnet id
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "authenticator", "audit", "controllerManager", "scheduler"]
    logRetentionInDays: 30
