name: Push to ECR

on:
  workflow_run:
    workflows:
      - Lint and Test
    types:
      - completed

env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credential
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, Push Docker Image to ECR
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        IMAGE_TAG: $(date +'%Y-%m-%d-%H-%M')  # 西暦、日付、時間（例: 2024-11-30-14-25）
        REPOSITORY_NAME: eks-demo-ecr
      run: |
        # Build Docker image with a dynamic tag (based on date and time)
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG ./app
        
        # Tag Docker image
        docker tag $AWS_ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG \
          $AWS_ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
        
        # Push Docker image to ECR
        docker push $AWS_ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG

