name: Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install pylint requests

    - name: Run Lint Test
      run: pylint app/*.py --exit-zero

    - name: Build Docker Image
      run: docker build -t streamlit-app:latest ./app

    - name: Scan with Inspector
      id: inspector
      uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1
      with:
        artifact_type: 'container'
        artifact_path: streamlit-app:latest

    - name: Stop the build if vulnerabilities are detected # works with Trivy(aquasecurity/trivy-action@master) too
      if: ${{ steps.inspector.outputs.vulnerability_threshold_exceeded == 'true' }}
      run: |
        echo "High or Critical vulnerabilities detected. Stopping the build."
        exit 1

    - name: Run Docker Image
      run: docker run -d -p 8501:8501 --name streamlit-app streamlit-app:latest

    - name: Run HTTP Request Test
      run: python app/test/http-test.py

    - name: Stop and Remove Docker Image
      run: |
        docker stop streamlit-app
        docker rm streamlit-app
